components_manager:
    task_processors:                  # Task processor is an executor for coroutine tasks

        main-task-processor:          # Make a task processor for CPU-bound coroutine tasks.
            worker_threads: 2         # Process tasks in 4 threads.

        fs-task-processor:            # Make a separate task processor for filesystem bound tasks.
            worker_threads: 1

    default_task_processor: main-task-processor

    components:                       # Configuring components that were registered via component_list
        server:
            listener:                 # configuring the main listening socket...
                port: 8080            # ...to listen on this port and...
                task_processor: main-task-processor    # ...process incoming requests on this task processor.
        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stderr'
                    level: info
                    overflow_behavior: discard  # Drop logs if the system is too busy to write them down.

        # Dynamic config options. Cache is disabled, updates are disabled.
        dynamic-config:
            # For most of userver dynamic configs, defaults are used, some are overridden here.
            # See userver "dynamic config" docs for what configs exist.
            defaults:
                HTTP_CLIENT_CONNECTION_POOL_SIZE: 1000

        testsuite-support: {}

        http-client:
            load-enabled: false
            fs-task-processor: fs-task-processor

        dns-client:
            fs-task-processor: fs-task-processor

        tests-control:
            load-enabled: false
            path: /tests/{action}
            method: POST
            task_processor: main-task-processor
        handler-ping:
            path: /ping
            method: GET
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        repotest.ru:
          dir: /var/www/repotest.ru                  # Path to the directory with files
          update-period: 10s                         # update cache each N seconds
          fs-task-processor: fs-task-processor       # Run it on blocking task processor

        wordle-task.repotest.ru:
          dir: /var/www/wordle-task.repotest.ru      # Path to the directory with files
          update-period: 10s                         # update cache each N seconds
          fs-task-processor: fs-task-processor       # Run it on blocking task processor

        handler-subdomain-static: # Finally! Static handler.
            fs-cache-storages:  [repotest.ru, wordle-task.repotest.ru]
            path: /*                  # Registering handlers '/*' find files.
            method: GET              # Handle only GET requests.
            task_processor: main-task-processor  # Run it on CPU bound task processor
